import os

class _NotModified:
    pass

NOT_MODIFIED = _NotModified()

# JWT
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", 30))
REFRESH_TOKEN_EXPIRE_MINUTES = int(os.getenv("REFRESH_TOKEN_EXPIRE_MINUTES", 60 * 24 * 7))

JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
JWT_REFRESH_SECRET_KEY = os.getenv("JWT_REFRESH_SECRET_KEY")

ALGORITHM = "HS256"

# AUTH
TOKEN_URL = "/auth/token"

# Permissions
SUPER_ADMIN_NAME = os.getenv("SUPER_ADMIN_NAME")

